# Generated by Django 4.0.3 on 2022-07-23 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cuadro',
            table='cuadros',
        ),
    ]
