# Generated by Django 4.0.4 on 2022-07-03 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_cuadro_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuadro',
            options={'ordering': ['name'], 'verbose_name': 'cuadro'},
        ),
        migrations.AddField(
            model_name='cuadro',
            name='author',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='paint', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
