# Generated by Django 4.0.4 on 2022-07-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_paint_author_paint_description_paint_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='on_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paint',
            name='img',
            field=models.ImageField(upload_to='L:\\programacion\\Backend\\Django Framework\\ProyectosDjango\\ArteApp\\DjangoBackend\\media/paintings/%Y/%m/%d'),
        ),
    ]
