# Generated by Django 4.0.3 on 2022-07-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_cuadro_author_cuadro_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuadro',
            options={'ordering': ['name'], 'verbose_name': 'cuadro', 'verbose_name_plural': 'Cuadros'},
        ),
        migrations.AlterModelTable(
            name='cuadro',
            table='Cuadros',
        ),
    ]
