# Generated by Django 4.0.4 on 2022-07-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_paint_on_sell_alter_paint_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='img',
            field=models.ImageField(upload_to='paintings/%Y/%m/%d'),
        ),
    ]
